# Site settings
title: Paul Crosby
email: paul71crosby@gmail.com
url: https://www.paul-crosby.co
description: "From Banking to Building."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: www.paul-crosby.co

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/@crozza71
  - title: linkedin
    url: https://uk.linkedin.com/in/paul-crosby
  - title: github
    url: https://github.com/Crozza71

# Build settings
markdown: kramdown
permalink: pretty
